### PR TITLE
Documentation and type changes

### PR DESCRIPTION
**Pull request by brokenprogrammer**
### Description
This is in response to #33 With the goal to fix failing tests. Add additional documentation and look over bad types not following the API documentation.

Adds documentation and corrected types to the following Models:
* AbsenceTransactions
* Assets
* Account
* AccountChart
* Archive
* Article
* AssetType
* AttendanceTransaction
* Authorization
* CompanyInformation
* CompanySettings
* Contract
* ContractTemplates
* CostCenter
* Currency
* Customer
* Inbox

### Checklist
- [X] Code compiles correctly
- [X] Created tests which fail without the change (if possible)
- [X] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by brokenprogrammer** [comment]
I'll take a look at the failing builds on monday next week when I have access to my work PC. 
I think the builds are failing due to some kind of Fortnox update in the Offers module as they were working before but now suddenly started to complain about housework types.

I also think its time to start fixing theese tests once and for all.

**Comment by brokenprogrammer** [comment]
This seems to be the reason for the failing tests: https://developer.fortnox.se/blog/updates-in-tax-reduction/

**Comment by brokenprogrammer** [comment]
Published Pre-Release version of Fortnox.NET Version 3.0.0 to NuGet: https://www.nuget.org/packages/Fortnox.NET/3.0.0-alpha

This PR will be opened unitll we are done with #33 after discussion with @GGAlanSmithee

**Comment by brokenprogrammer** [comment]
Published Pre-Release version of Fortnox.NET Version 3.0.0 to NuGet: https://www.nuget.org/packages/Fortnox.NET/3.0.0-alpha2

Resolves #36

**Comment by brokenprogrammer** [comment]
Published Pre-Release version of Fortnox.NET Version 3.0.0 to NuGet: https://www.nuget.org/packages/Fortnox.NET/3.0.0-alpha3

Related to #40

**Comment by GGAlanSmithee** [comment]
Awesome job @brokenprogrammer

**Pull request merged**
