### PR TITLE
Added ELECTRONICINVOICE to DeliveryType ENUM

### PR DESCRIPTION
**Pull request by brakim**
### Description
Please explain the changes you made here.

### Checklist
- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by brokenprogrammer** [comment]
Thank you @brakim for showing interest in the project. 

I looked over the new fortnox documentation which is supposed to be auto-generated based of their API but cannot see `ELECTRONICINVOICE` specified under Customer's DefaultDeliveryTypes. [Fortnox Documentation Get CustomerResource](https://apps.fortnox.se/apidocs#operation/get_CustomersResource)

Where can I learn more about this and do you perhaps know why it's not documented?

**Comment by kwestground** [comment]
@brokenprogrammer This seems to be an undocumented option, if you take a look at Fortnox SDK they got it.

[csharp-api-sdk/FortnoxSDK/Entities/Customers/DefaultDeliveryType.cs](https://github.com/FortnoxAB/csharp-api-sdk/blob/master/FortnoxSDK/Entities/Customers/DefaultDeliveryType.cs)

**Comment by brokenprogrammer** [comment]
@brakim @kwestground I have reached out to my contact over at Fortnox to verify this.

**Comment by brakim** [comment]
We have a production example when https://api.fortnox.se/3/customers/{id} returns 

```
"DefaultDeliveryTypes": {
     "Invoice": "ELECTRONICINVOICE"
}
```

**Comment by brokenprogrammer** [comment]
@brakim I got an answer from Fortnox and this is indeed a mistake in their documentation. 
Could you please re-make this PR so that you make it from and to my branch feature/type-changes 

This is so that I can make a new alpha release for you guys tomorrow morning.

**Comment by brakim** [comment]
See #40

**Pull request closed without merging**
